baseURL = 'https://agneskis.dev/'
googleAnalytics = "G-LS8T3JPE59"

languageCode = 'en-us'
theme = "PaperMod"

title = 'Ágnes Kis'

[caches]
[caches.images]
dir = ':cacheDir/images'

[params]
ShowShareButtons = true
ShowPinnedPosts = true
ShowPinnedPostsOnHome = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true

[markup]
[markup.goldmark.renderer]
unsafe = true

[params.homeInfoParams]
Title = "Hi 👋"
Content = '''
<p>You just found my personal website, where I introduce myself and share information about my work and interests.</p>

<br>

<p>I am a full stack software engineer with a passion for creating nice things, and getting a wide variety of knowledge to enable me to do so.</p>

<br>

<p>I hope you'll find something interesting here! 🐦‍⬛</p>
'''

[params.socialIcons]
[params.socialIcons.github]
name = "GitHub"
url = "https://github.com/agnesk92"

[params.socialIcons.bluesky]
name = "bluesky"
url = "https://bsky.app/profile/gneska.bsky.social"

[params.socialIcons.linkedin]
name = "linkedin"
url = "https://www.linkedin.com/in/agneskis"

[params.socialIcons.stackoverflow]
name = "stackoverflow"
url = "https://stackoverflow.com/users/11078901/agnes-kis"

[params.socialIcons.rss]
name = "rss"
url = "http://localhost:1313/index.xml"

[languages]

[languages.EN]
title = 'Ágnes Kis'
weight = 1
contentDir = "content/en"
languageName = "English"

[languages.EN.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[languages.EN.menu.main]]
name = "About me"
url = "about"
weight = 10

[[languages.EN.menu.main]]
name = "Posts"
url = "posts"
weight = 1

# [[languages.EN.menu.main]]
# name = "Search"
# url = "search/"
# weight = 10

# [[languages.EN.menu.main]]
# name = "Tags"
# url = "tags/"
# weight = 10

# Todo!
# [languages.DA]
